djangoapps/urls.py
from django.contrib import admin
from django.urls import path, re_path

from baseball import views as baseball_vw

urlpatterns = [
    re_path(r'^admin/', admin.site.urls),
    re_path(r'^$', baseball_vw.project_markdown),
    # re_path(r'^runJobs/', baseball_vw.run_jobs_view),
    re_path(r'^viewStats/', baseball_vw.stats_view),
    re_path(r'^project/', baseball_vw.project_markdown),
    re_path(r'^jobs-dashboard/', baseball_vw.jobs_dashboard2),
    re_path(r'ajax/load-teams/', baseball_vw.load_teams, name='ajax_load_teams'),
    re_path(r'api/stat_results', baseball_vw.StatsResults2.as_view(), name='api_get_stats'),
    re_path(r'flowchart/', baseball_vw.process_flowchart),
    re_path(r'api/fav_players', baseball_vw.FavPlayers.as_view(), name='api_fav_players'),
    re_path(r'fav-players/', baseball_vw.fav_players)
]

baseball/models.py
from django.db import models
from .oper import date_time as dt

# CHOICES
WHICH_TEAM = [('away', 0), ('home', 1)]
PLAY_TYPE = [('play', 'play'), ('sub', 'sub')]
STAT_CATEGORY = [('batting', 0), ('pitching', 1), ('defense', 2)]

# constants
YEARS = dt.gen_year()
TEAMS = (('ANA', 'ANA'), ('ARI', 'ARI'), ('ATL', 'ATL'), ('BAL', 'BAL'), ('BOS', 'BOS'), ('CHA', 'CHA'),
         ('CHN', 'CHN'), ('CIN', 'CIN'), ('CLE', 'CLE'), ('COL', 'COL'), ('DET', 'DET'), ('HOU', 'HOU'),
         ('KCA', 'KCA'), ('LAN', 'LAN'), ('MIA', 'MIA'), ('MIL', 'MIL'), ('MIN', 'MIN'), ('NYA', 'NYA'),
         ('NYN', 'NYN'), ('OAK', 'OAK'), ('PHI', 'PHI'), ('PIT', 'PIT'), ('SDN', 'SDN'), ('SEA', 'SEA'),
         ('SFN', 'SFN'), ('SLN', 'SLN'), ('TBA', 'TBA'), ('TEX', 'TEX'), ('TOR', 'TOR'), ('WAS', 'WAS'))
FORM_TYPE = (('import_year', 'import_year'), ('process_team', 'process_team'), ('generate_stats', 'generate_stats'),
             ('view_stats', 'view_stats'))
PLAYERS = [
        {'name': 'Ichiro Suzuki', 'playerID': 'suzui001', 'stat_type': 'batting'},
        {'name': 'Roy Halladay', 'playerID': 'hallr001', 'stat_type': 'pitching'},
        {'name': 'Clayton Kershaw', 'playerID': 'kersc001', 'stat_type': 'pitching'},
        {'name': 'Mookie Betts', 'playerID': 'bettm001', 'stat_type': 'batting'},
        {'name': 'Justin Verlander', 'playerID': 'verlj001', 'stat_type': 'pitching'},
        {'name': 'Matt Stairs', 'playerID': 'staim001', 'stat_type': 'batting'}
    ]


# Extract/Process Requests
class JobRequirements(models.Model):
    year = models.IntegerField(choices=YEARS)
    team = models.CharField(max_length=4, choices=TEAMS)
    form_type = models.CharField(max_length=20, choices=FORM_TYPE, null=True, default=None)

    def __str__(self):
        return str(self.year) + str(self.team) + str(self.form_type)


# Teams
class Team(models.Model):
    team_id = models.CharField(max_length=15)
    team_city = models.CharField(max_length=25)
    team_name = models.CharField(max_length=15)

    def __str__(self):
        return self.team_name


# Game Info
class GameInfo(models.Model):
    game_id = models.CharField(max_length=12)
    home_team = models.ForeignKey(Team, null=True, on_delete=models.SET_NULL, related_name='_home_team')
    away_team = models.ForeignKey(Team, null=True, on_delete=models.SET_NULL, related_name='_away_team')
    game_info = models.CharField(max_length=100)

    def __str__(self):
        return self.game_id


# Players
class Player(models.Model):
    player_id = models.CharField(max_length=10)
    first_name = models.CharField(max_length=20)
    last_name = models.CharField(max_length=25)

    def __str__(self):
        return self.player_id


# Starters
class Starter(models.Model):
    game_id = models.ForeignKey(GameInfo, null=True, on_delete=models.SET_NULL)
    away_1 = models.ForeignKey(Player, null=True, on_delete=models.SET_NULL, related_name='_away_1')
    away_2 = models.ForeignKey(Player, null=True, on_delete=models.SET_NULL, related_name='_away_2')
    away_3 = models.ForeignKey(Player, null=True, on_delete=models.SET_NULL, related_name='_away_3')
    away_4 = models.ForeignKey(Player, null=True, on_delete=models.SET_NULL, related_name='_away_4')
    away_5 = models.ForeignKey(Player, null=True, on_delete=models.SET_NULL, related_name='_away_5')
    away_6 = models.ForeignKey(Player, null=True, on_delete=models.SET_NULL, related_name='_away_6')
    away_7 = models.ForeignKey(Player, null=True, on_delete=models.SET_NULL, related_name='_away_7')
    away_8 = models.ForeignKey(Player, null=True, on_delete=models.SET_NULL, related_name='_away_8')
    away_9 = models.ForeignKey(Player, null=True, on_delete=models.SET_NULL, related_name='_away_9')
    away_10 = models.ForeignKey(Player, null=True, on_delete=models.SET_NULL, related_name='_away_10')
    home_1 = models.ForeignKey(Player, null=True, on_delete=models.SET_NULL, related_name='_home_1')
    home_2 = models.ForeignKey(Player, null=True, on_delete=models.SET_NULL, related_name='_home_2')
    home_3 = models.ForeignKey(Player, null=True, on_delete=models.SET_NULL, related_name='_home_3')
    home_4 = models.ForeignKey(Player, null=True, on_delete=models.SET_NULL, related_name='_home_4')
    home_5 = models.ForeignKey(Player, null=True, on_delete=models.SET_NULL, related_name='_home_5')
    home_6 = models.ForeignKey(Player, null=True, on_delete=models.SET_NULL, related_name='_home_6')
    home_7 = models.ForeignKey(Player, null=True, on_delete=models.SET_NULL, related_name='_home_7')
    home_8 = models.ForeignKey(Player, null=True, on_delete=models.SET_NULL, related_name='_home_8')
    home_9 = models.ForeignKey(Player, null=True, on_delete=models.SET_NULL, related_name='_home_9')
    home_10 = models.ForeignKey(Player, null=True, on_delete=models.SET_NULL, related_name='_home_10')

    def __str__(self):
        return self.game_id


# Game Plays
class GamePlay(models.Model):
    game_id = models.ForeignKey(GameInfo, null=True, on_delete=models.SET_NULL)
    type_of_play = models.CharField(max_length=4, choices=PLAY_TYPE)
    inning = models.IntegerField()
    which_half = models.IntegerField(choices=WHICH_TEAM)
    half_innings = models.CharField(max_length=4)
    player_id = models.ForeignKey(Player, null=True, on_delete=models.SET_NULL, related_name='_player')
    pitch_count = models.CharField(max_length=2)
    pitches = models.CharField(max_length=30)
    the_play = models.CharField(max_length=40)
    # player_name -- does this need reference?
    which_team = models.IntegerField(choices=WHICH_TEAM)
    team_name = models.ForeignKey(Team, null=True, on_delete=models.SET_NULL)
    batting_spot = models.IntegerField()
    fielding_pos = models.IntegerField()
    pitcher_id = models.ForeignKey(Player, null=True, on_delete=models.SET_NULL, related_name='_pitcher')
    num_of_outs = models.IntegerField()
    before_1b = models.CharField(max_length=12)
    before_2b = models.CharField(max_length=12)
    before_3b = models.CharField(max_length=12)
    after_1b = models.CharField(max_length=12)
    after_2b = models.CharField(max_length=12)
    after_3b = models.CharField(max_length=12)
    runs_scored = models.IntegerField()
    total_scored = models.IntegerField()

    def __str__(self):
        return str(self.game_id) + ': ' + str(self.half_innings) + ' - ' + str(self.the_play)


# Stat Collector
class StatCollect(models.Model):
    player_id = models.ForeignKey(Player, null=True, on_delete=models.SET_NULL)
    team_name = models.CharField(max_length=3)
    game_id = models.ForeignKey(GameInfo, null=True, on_delete=models.SET_NULL)
    half_inning = models.CharField(max_length=4)
    stat_type = models.CharField(max_length=5)
    stat_value = models.IntegerField()
    actual_play = models.CharField(max_length=40)
    num_of_outs = models.IntegerField()
    bases_taken = models.CharField(max_length=3)
    stat_team = models.IntegerField(choices=WHICH_TEAM)
    stat_category = models.CharField(max_length=8, choices=STAT_CATEGORY)

    def __str__(self):
        return str(self.player_id) + ' stat for ' + str(self.stat_type) + ': ' + str(self.stat_value)


# FavPlayers
class FavPlayers(models.Model):
    name = models.CharField(max_length=50, choices=[(p['playerID'], p['name']) for p in PLAYERS])
    
    def __str__(self):
        return str(self.name)

baseball/forms.py
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Fieldset, ButtonHolder, Submit
from crispy_forms.bootstrap import InlineRadios
import os
import numpy as np
from .models import JobRequirements, FavPlayers
# from .oper import check_latest_imports as chk
from .oper2 import common_functions as cf2


class GetYear(forms.ModelForm):

    year = cf2.get_years_list()

    def __init__(self, year_choices, *args, **kwargs):
        super(GetYear, self).__init__(*args, **kwargs)
        self.fields['year'].choices = year_choices

    class Meta:
        model = JobRequirements
        fields = ['year', 'form_type']
        widgets = {'form_type': forms.HiddenInput()}


class ProcessTeam(forms.ModelForm):

    year = [2019]
    team = cf2.get_teams_list(2019)

    def __init__(self, year_choices, team_choices, *args, **kwargs):
        super(ProcessTeam, self).__init__(*args, **kwargs)
        self.fields['year'].choices = year_choices
        self.fields['team'].choices = team_choices

    class Meta:
        model = JobRequirements
        fields = ['year', 'team', 'form_type']
        widgets = {'form_type': forms.HiddenInput()}


class GenerateStats(forms.ModelForm):
    
    year = [2019]
    team = cf2.get_teams_list(2019)

    def __init__(self, year_choices, team_choices, *args, **kwargs):
        super(GenerateStats, self).__init__(*args, **kwargs)
        self.fields['year'].choices = year_choices
        self.fields['team'].choices = team_choices

    class Meta:
        model = JobRequirements
        fields = ['year', 'team', 'form_type']
        widgets = {'form_type': forms.HiddenInput()}


class ViewStats(forms.ModelForm):

    def __init__(self, year_choices, team_choices, *args, **kwargs):
        super(ViewStats, self).__init__(*args, **kwargs)
        self.fields['year'].choices = year_choices
        self.fields['team'].choices = team_choices

    class Meta:
        model = JobRequirements
        fields = ['year', 'team', 'form_type']
        widgets = {'form_type': forms.HiddenInput()}


#  -----  FAV PLAYERS DASHBOARD  -----  #
class GetFavPlayer(forms.ModelForm):
    
    def __init__(self, players, *args, **kwargs):
        super(GetFavPlayer, self).__init__(*args, **kwargs)
        self.fields['name'].choices = [(p['playerID'] + ';' + p['stat_type'], p['name']) for p in players]
        
    class Meta:
        model = FavPlayers
        fields = ['name']

baseball/templates/pages/analyzeStats.html
{% include 'partials/header_baseball.html' %}
    <div id="my_title" class="d-flex justify-content-center">
        <h1>My Fav Players Dashboard</h1>
    </div><br>

    {% load crispy_forms_tags %}
    <!--form id="view_stats" action="" method="post" data-teams-url="{% url 'ajax_load_teams' %}" novalidate>
        {% csrf_token %}
        {{ form_view_stats.as_table }}
        <input type="submit" value="View Stats">
    </form>

    <div id="selected" class="d-flex justify-content-center">
        <h3>{{ heading }}</h3>
    </div><br>
    <div id="table_output" class="d-flex justify-content-center"></div>

    <script>
        (function () {
            window.results = JSON.parse('{{results|safe}}');
            window.columns = {{post_col|safe}};
            window.bat_col = JSON.parse('{{col_convert|safe}}');
        }());
    </script-->
    {% load static %}
    <!--script src="{% static 'scripts/baseball_view_stats.js' %}"></script-->
    <br>

    <!--script>
    // for the teams drop-down dependency
    $("#id_year").change(function () {
        var url = $("#view_stats").attr("data-teams-url");  // get the url of the `load_teams` view
        var yearId = $(this).val();  // get selected YEAR
        console.log(url);
        // initialize an AJAX request
        $.ajax({
            //async: true,
            url: url,  // set the url of the request (= localhost:8000/ajax/load-teams/)
            data: {
                'year': yearId  // add the year id to the GET parameters
            },
            success: function (data) {  // `data` is the return of the `load_teams` view function
                console.log(data);
                $("#id_team").html(data);  // replace with the values retrieved
            }
        });
    });
    </script-->

{% include 'partials/footer_baseball.html' %}

baseball/templates/pages/favPlayers.html
{% include 'partials/header_baseball.html' %}
    <div id="my_title" class="d-flex justify-content-center">
        <h1>My Fav Players Dashboard</h1>
    </div><br>

    <div class="d-flex justify-content-center">
        <div class="col-md-2"></div>
        <div class="col-md-8">
            <p>Here is a dashboard for some of my favourite players.</p>
        </div>
        <div class="col-md-2"></div>
    </div>

    {% load crispy_forms_tags %}
    <div class="d-flex justify-content-center">
        <div class="col-md-2"></div>
        <div class="col-md-8">
            <form id="fav_player_form">
                {% csrf_token %}
                {{ favForm.as_table }}
            </form>
        </div>
        <div class="col-md-2"></div>
    </div>

    <div>
        <div id="dashboard1" class="d-flex justify-content-center">

        </div>
        <div class="d-flex justify-content-center">
            <div class="col-md-4"></div>
            <div id="below-dash" class="col-md-4"></div>
            <div class="col-md-4"></div>
        </div>
    </div>
    <div><br><br></div>
    <div id="dashboard2" class="d-flex justify-content-center"></div>

    {% load static %}
    <script src="https://d3js.org/d3-scale.v3.min.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js" integrity="sha256-VazP97ZCwtekAsvgPBSUwPFKdrwD3unUfSGVYrahUqU=" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.0/themes/smoothness/jquery-ui.css">
    <script src="{% static 'scripts/baseball/dashboard_favPlayer.js' %}"></script>
    <script src="{% static 'scripts/baseball/similarity_graphs.js' %}"></script>
    <script src="{% static 'scripts/baseball/circular_barplot.js' %}"></script>
    <br>

    <script>
    // players drop down menu
    $("#id_fav_players-name").change(function () {
        var url = '/api/fav_players';  // get the url of fav players API
        var playerID = $(this).val().split(';')[0]
        var stat_type = $(this).val().split(';')[1]
        var output;

        // initialize an AJAX request
        $.ajax({
            url: url,
            data: {
                'playerID': playerID,
                'stat_type': stat_type
            },
            success: function (data) {
                output = data;

                // change up the dashboard
                api_response(output);
            }
        });
    });

    // variables from django
    (function () {
        window.results = {{ results|safe }};
        window.mainStat = results.mainStat;
        window.aggStats = results.aggStats;
        window.circleBarData = results.circleBarData;
        window.simData = results.simData;
        window.simScores = results.simScores;
        window.playerNames = results.playerNames;
        window.retroIDs = Object.keys(simData);
    }());

    // set slider
    $(document).ready(function() {

        // create slider
        slider_create();

        // set slider
        var min_year = d3.min(circleBarData, d => d.year);
        $("#year-slider").slider({
            max: +d3.max(circleBarData, d => d.year),
            min: +min_year,
            step: 1,
            slide: function(event, ui){
                year_index = ui.value - min_year;
                updateYear(year_index, min_year);
            }
        })
    });

    // variables
    var lineChart0, lineChart1, lineChart2, lineChart3, lineChart4;
    var lineChart5, lineChart6, lineChart7, lineChart8, lineChart9;
    var minAge, maxAge, minFit, maxFit;
    var circleBarPlot;
    var yearSelected = 2001;

    // set stat boxes
    stats = statBoxData(aggStats, mainStat);
    changeStatBox1();
    changeStatBox2();
    changeStatBox3();

    // set circle bar plot
    circleBarData = dataKeyPair(circleBarData);

    // set similarity graphs and scores
    similarityDataChange(simData);
    sim_scores_update(simScores);

    // declare graphs
    lineChart0 = new LineChart('#simLine0', 150, 150, 0);
    lineChart1 = new LineChart('#simLine1', 150, 150, 1);
    lineChart2 = new LineChart('#simLine2', 150, 150, 2);
    lineChart3 = new LineChart('#simLine3', 150, 150, 3);
    lineChart4 = new LineChart('#simLine4', 150, 150, 4);
    lineChart5 = new LineChart('#simLine5', 150, 150, 5);
    lineChart6 = new LineChart('#simLine6', 150, 150, 6);
    lineChart7 = new LineChart('#simLine7', 150, 150, 7);
    lineChart8 = new LineChart('#simLine8', 150, 150, 8);
    lineChart9 = new LineChart('#simLine9', 150, 150, 9);
    circleBarPlot = new CircleBarPlot('#circleBar', 500, 500, 'suzui001');

    // handling the API response
    function api_response(data) {

        // get data
        results = data.results;

        // set variables
        mainStat = results.mainStat;
        aggStats = results.aggStats;
        stats = statBoxData(aggStats, mainStat);
        circleBarData = dataKeyPair(results.circleBarData);
        simData = results.simData;
        simScores = results.simScores;

        // change stat boxes
        changeStatBox1();
        changeStatBox2();
        changeStatBox3();

        // delete slider and create again
        var slider = document.getElementById("slider-div")
        slider.parentNode.removeChild(slider);
        slider_create();

        // set slider
        var min_year = d3.min(circleBarData, d => d.year);
        $("#year-slider").slider({
            max: +d3.max(circleBarData, d => d.year),
            min: +min_year,
            step: 1,
            slide: function(event, ui){
                year_index = ui.value - min_year;
                updateYear(year_index, min_year);
            }
        })

        // set Year label and yearSelected
        document.getElementById("year").textContent = min_year;
        yearSelected = min_year;

        // update simData, simScores details
        playerNames = results.playerNames;
        similarityDataChange(simData);
        sim_scores_update(simScores);

        // update simData description
        document.getElementById("trajectory-description").textContent = (mainStat == 'batting') ? 'based on OPS': 'based on WHIP';

        // adjust all the plots
        circleBarPlot.wrangleData();
        lineChart0.wrangleData();
        lineChart1.wrangleData();
        lineChart2.wrangleData();
        lineChart3.wrangleData();
        lineChart4.wrangleData();
        lineChart5.wrangleData();
        lineChart6.wrangleData();
        lineChart7.wrangleData();
        lineChart8.wrangleData();
        lineChart9.wrangleData();
    };
    </script>

{% include 'partials/footer_baseball.html' %}

baseball/templates/pages/flowchart.html
{% include 'partials/header_mermaid.html' %}


    <div id="my_title" class="d-flex justify-content-center">
        <h1>Baseball Project Flowchart</h1>
    </div><br>
    <div class="mermaid">
        graph TB
            subgraph importYear
                S1[Start] --> A1[Get all files]
                A1 --> A2[Sort into Folder]
                A2 --> A3[Finish]
            end

            subgraph extractNames
                A3 --> S2
                S2[Start] --> B1[Extract Team Names]
                B1 --> B2[Extract all Player Names]
                B2 --> B3[Sort Both into Database]
                B3 --> B4[Finish]
            end

            subgraph processTeam
                B4 --> S3
                S3[Start] --> C[Loop thru file]
                C --> C1{If End of File}
                C1 --> |Yes|FN[Finish]
                C1 --> |No|D{Type of Play}
                D -->|Non-Plate Appearance| E1[Process Play]
                D -->|Plate Appearance| E2[Process Play]
                D -->|Substitution| E3[Handle Substitute]
                E2 --> E4[Handle Batter]
                E1 --> F[Record Raw Stats]
                E4 --> F
                E3 --> F
                F --> F1[Move Baserunners]
                F1 --> F2[Handle Current Half Inning]
                F2 --> |Next play|C
            end

            subgraph generateStats
                FN --> S4
                S4[Start] --> G1{Type of Stat}
                G1 --> |Batting|G3[Grab Raw Stats]
                G1 --> |Pitching|G3
                G1 --> |Fielding|G3
                G3 --> G4[Aggregate & Tally]
                G4 --> G5[Insert to Database]
                G5 --> H{If Test Case Exists}
                H --> |Yes|H1[Run Test Cases]
                H --> |No|H2[Finish]
            end
    </div>
    <br>
    <script>mermaid.initialize({startOnLoad:true});</script>

{% include 'partials/footer_baseball.html' %}

baseball/templates/pages/homepage.html
{% include 'partials/header_baseball.html' %}
    <h1>Welcome</h1>
    <div id="startContent" class="container-fluid">

    <p>Edit this page later...</p>
    </div>

{% include 'partials/footer_baseball.html' %}

baseball/templates/pages/jobsDashboard.html
{% include 'partials/header_baseball.html' %}
    <div id="my_title" class="d-flex justify-content-center">
        <h1>Jobs Dashboard</h1>
    </div><br>

    <div id="startContent" class="d-flex justify-content-center">


    </div><br>

    <script>
        (function () {
                window.processes = JSON.parse('{{processes|safe}}');
                window.years_imported = JSON.parse('{{years_imported|safe}}');
                window.teams_processed = JSON.parse('{{teams_processed|safe}}');
                // use years_imported if no teams processed yet
                if (teams_processed.length == 0) {
                    window.teams_processed = years_imported;
                }
                window.stats_generated = JSON.parse('{{stats_generated|safe}}');
                window.recent_10 = JSON.parse('{{recent_10|safe}}');
                window.recent_10_min_time = new Date({{recent_10_min_time|safe}});
                window.recent_10_max_time = new Date({{recent_10_max_time|safe}});
                window.max_time_elapsed = {{recent_10_max_elapsed|safe}};
                window.error_rate = {{error_rate|safe}};
                window.team_data = {{team_data|safe}};
                window.max_hits = {{max_hits|safe}};
                window.max_hrs = {{max_hrs|safe}};
                window.min_hits = {{min_hits|safe}};
                window.min_hrs = {{min_hrs|safe}};
                // window.num_teams_array = {{num_teams_array|safe}};

                /* #### parameters #### */
                // overall progress - reuse window sizes as well
                window.grid_width = 120;
                window.grid_height = 310;
                window.bar_height = 30;
                window.bar_spacing = 10 + bar_height;
                window.op_trans = 1000; // overall progress bar transition time (ms)
                window.view_height = grid_height + 100;
                window.view_width = grid_width * processes.length + 150;

                // recent 10 completions
                window.recent_start_x = view_width + 25;

                window.svg_height = view_height * 2 + 50;
                window.svg_width = view_width * 2 + 25;
            }());
    </script>
    {% load static %}
    <script src="{% static 'scripts/baseball/dashboard_overall.js' %}"></script>
    <script src="{% static 'scripts/baseball/dashboard_recent.js' %}"></script>
    <script src="{% static 'scripts/baseball/dashboard_error_pie.js' %}"></script>
    <script src="{% static 'scripts/baseball/dashboard_leaders.js' %}"></script>

{% include 'partials/footer_baseball.html' %}

baseball/templates/pages/viewStats.html
{% include 'partials/header_viewStats.html' %}
    <div id="my_title" class="d-flex justify-content-center">
        <h1>View Team Stats</h1>
    </div><br>

    {% load crispy_forms_tags %}
    <form id="view_stats" method="post" data-teams-url="{% url 'ajax_load_teams' %}" novalidate>
        {% csrf_token %}
        {{ form_view_stats.as_table }}
        <!--input type="submit" value="View Stats"-->
    </form>


    <div class="col-1">
        <div class="switch-toggle switch-3 switch-candy">
            <input id="batting" name="state-d" type="radio" value="batting" checked="checked" />
            <label class="stat_state" for="batting" onclick="">batting</label>

            <input id="pitching" name="state-d" type="radio" value="pitching" />
            <label class="stat_state" for="pitching" onclick="">pitching</label>

            <input id="fielding" name="state-d" type="radio" value="fielding" />
            <label class="stat_state" for="fielding" onclick="">fielding</label>

            <a></a>
        </div>
    </div>

    <div class="d-flex justify-content-center">
        <h3 id="select_header">2019 Batting Stats for ANA</h3>
    </div><br>
    <div id="table_div" class="d-flex justify-content-center">
        <table id="table_output" class="display" width="100%"></table><br>
    </div><br>
    <script>
    // for the teams drop-down dependency
    $("#id_year").change(function () {
        var url = $("#view_stats").attr("data-teams-url");  // get the url of the `load_teams` view
        var yearId = $(this).val();  // get selected YEAR
        //console.log(url);
        // initialize an AJAX request
        $.ajax({
            //async: true,
            url: url,  // set the url of the request (= localhost:8000/ajax/load-teams/)
            data: {
                'year': yearId  // add the year id to the GET parameters
            },
            success: function (data) {  // `data` is the return of the `load_teams` view function
                //console.log(data);
                $("#id_team").html(data);  // replace with the values retrieved
            }
        });
    });

    // get request for the DataTable stats
    $(document).ready(function() {
        window.col_types = {{col_types|safe}};

        // instantiate DataTable
        table_instantiate();
    });

    // new GET request call every time the team name is changed
    $("#id_team").change(function () {
        getURL = "/api/stat_results?format=datatables&year=" + $("#id_year").val()  +
            "&team=" + $("#id_team").val() + "&stats_table=" + $("input[name=state-d]:checked").val();
        //console.log(getURL);
        table.ajax.url(getURL).load();

        // update the header
        update_header();
    });

    // new GET request when stat type is toggled (batting, pitching, fielding)
    $(".switch-candy").change(function() {

        // destroy the table, then setup a new table
        table.destroy(true);
        var get_div = document.getElementById("table_div");
        var new_table = document.createElement("table");
        new_table.setAttribute("id", "table_output");
        new_table.setAttribute("class", "display");
        new_table.setAttribute("width", "100%");
        get_div.appendChild(new_table);

        // instantiate the table
        table_instantiate();

        //console.log("switch toggled");

        // update header
        update_header();
    });

    // function to instantiate DataTable
    function table_instantiate() {
        getURL = "/api/stat_results?format=datatables&year=" + $("#id_year").val() +
            "&team=" + $("#id_team").val() + "&stats_table=" + $("input[name=state-d]:checked").val();
        console.log(getURL);

        // instantiate the table
        table = $('#table_output').DataTable({
            "ajax": getURL,
            "columns": col_types[$("input[name=state-d]:checked").val()]['column_name'],
            "paging": false
        });

        // add the title to use for tool tip later
        $('#table_output thead tr th').each( function() {
            var sTitle;
            var nTds = $(this);
            var sTip = $(nTds[0]).text();
            //console.log(sTip);
            var sDesc = col_types[$("input[name=state-d]:checked").val()]['column_desc'][sTip];
            //console.log(sDesc);
            this.setAttribute('title', sDesc);
        });
    };

    // function to update header
    function update_header() {
        var stat_select = $("input[name=state-d]:checked").val();
        var first_letter = stat_select.charAt(0).toUpperCase();
        stat_select = first_letter + stat_select.slice(1); // skip first letter
        //console.log(stat_select);
        $("#select_header").text($("#id_year").val() + " " + stat_select + " Stats for " + $("#id_team").val());
    };
    </script>

{% include 'partials/footer_baseball.html' %}